import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Component/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Adnan Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
        <Header/>
        </header>
        <main style={{ width: "100vw", height: "87vh" }}>
        {children}
        </main>
        <footer>
          <p style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
            Footer
          </p>
        </footer>
      </body>
    </html>
  );
}
